# Generated by Django 2.2.10 on 2020-04-04 17:45

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('syllabus', models.FileField(blank=True, null=True, upload_to='course_files', validators=[api.validators.validate_extension])),
                ('logo', models.ImageField(blank=True, null=True, upload_to='course_files', validators=[api.validators.validate_file_size])),
            ],
        ),
    ]
