# Generated by Django 2.2.10 on 2020-03-02 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offlineproduct',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='onlineproduct',
            name='created_at',
        ),
    ]
