# Generated by Django 2.2.10 on 2020-04-14 18:28

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='product_files', validators=[api.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='service',
            name='extra_description',
            field=models.FileField(blank=True, null=True, upload_to='product_files', validators=[api.validators.validate_extension]),
        ),
    ]
