# Generated by Django 2.2.10 on 2020-04-15 10:10

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', users.models.MyUserManager()),
            ],
        ),
    ]
